### ISSUE TITLE
"apidump --out" creates empty folder / no har file?

### ISSUE THREAD

**Issue by christian-korneck** [akitasoftware/akita-cli#11]
I'm trying to use `akita apidump` with `--out` to a local folder. The out folder gets created but is empty. I've tried both on MacOS and Linux, both built from source and with the official binary (mentioned in the docs) and got the same result. Am I doing anything wrong?

**Results received:**
Empty out folder, no `.har` file.

**Expected:**
`.har` file gets created in the out dir.

**Example:**

Before: out dir doesn't exist:
```
$ ls -a
.  .. 
```

running as user root:

```
$ akita apidump -c 'curl -I -L https://api.github.com/users/torvalds/events/public' -u root --out ./dumpdir
[INFO] Running learn mode on interfaces lo, ens18, cni-podman0
[WARNING] --filter flag is not set, this means that:
[WARNING]   - all network traffic is treated as your API traffic
[WARNING]   - outbound witness collection is disabled
[INFO] Running subcommand...


======= _AKITA_SUBCOMMAND_ =======
======= _AKITA_SUBCOMMAND_ =======
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  299k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/2 200
server: GitHub.com
<...>

======= _AKITA_SUBCOMMAND_ =======
======= _AKITA_SUBCOMMAND_ =======
[INFO] Subcommand finished successfully, stopping trace collection...
[INFO] Success! 🎉
```

After: out dir got created but is empty:
```
$ ls -a
.  ..  dumpdir
ls -a dumpdir/
.  ..
```

**Comment by christian-korneck** [comment]
Sorry for the noise. I was mistaken that `apidump` should work both for in- and outbound traffic. Dumping inbound traffic works fine. #close

**Comment by mgritter** [comment]
Hi, Christian. I think there are a couple things going on here, and the tool could be clearer about the results (or lack thereof).

apidump will work for outbound traffic as well if you include a filter; you can do --filter "port 443" or --filter "port 80"

However, because the connection is encrypted with HTTPS, the tool cannot see which URLs are being accessed.  A combination that worked for me is:

sudo bin/akita apidump -c 'curl -I -L http://api.github.com/users/torvalds/events/public' --out ./dumpdir -u root --filter "port 80"

But it is not very interesting because all it shows is the redirection to HTTPS.

**Comment by christian-korneck** [comment]
hi @mgritter,

ah, thanks a lot, now it makes sense.
Just hacked together [a little proxy server](https://github.com/glue-tools/jetis) (really bad code, but just to try) that listens on unencrypted http and translates `http://` urls to `https://` urls while proxying. Now I seem to be able to do:

```
$ jetis
starting proxy server on localhost:8888 ...
```

and

```
sudo akita apidump -c 'curl --proxy http://localhost:8888 http://api.github.com/users/torvalds/events/public' --out . -u root --filter "port 8888"
```

and I'm getting a 400 KB `.har` file with promising content. 🎉

(Maybe as a feature idea ... a built-in proxy in `akira apidump` might be useful, so you don't have to hook up another proxy tool like charles to record outgoing requests?)
